### ISSUE TITLE
I have a problem that it does not really work.

### ISSUE THREAD

**Issue by Dmxsir** [jh0ker/welcomebot#6]
I do not see all the options in my bot and the group that start with the ` /`.
when i type `/welcome`   in my group im getting `Sorry, only the person who invited me can do that.`
when i type `/help`  in my bot i see an errors 

i did add the bot to my group.

 ```
C:\Users\asaf\Desktop\Priusilbot-master\Priusilbot-master>py bot.py
C:\Users\asaf\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\messagehandler.py:123: UserWarning: Using a list of filters in MessageHandler is getting deprecated, please use bitwise operators (& and |) instead. More info: https://git.io/vPTbc.
  warnings.warn('Using a list of filters in MessageHandler is getting '
2018-02-22 11:09:20,615 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\asaf\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\asaf\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 206, in set_welcome
    parse_mode=ParseMode.HTML)
NameError: name 'ParseMode' is not defined
2018-02-22 11:09:20,618 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\asaf\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\asaf\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 183, in help
    parse_mode=ParseMode.MARKDOWN,
NameError: name 'ParseMode' is not defined
2018-02-22 11:09:20,620 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\asaf\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\asaf\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "bot.py", line 183, in help
    parse_mode=ParseMode.MARKDOWN,
NameError: name 'ParseMode' is not defined
```

**Comment by Dmxsir** [comment]
Why this is happening?
