### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by zimler** [jh0ker/welcomebot#8]
I'm trying to use your bot and am getting the following error: Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    from telegram import Emoji, ParseMode, TelegramError, Update
ImportError: cannot import name 'Emoji'

I did a pip install of python-telegram-bot. Any thoughts?

**Comment by allbinmani** [comment]
I am having the same problem..
- Created `virtualenv` for python3.6 with `` virtualenv -p `wich python3.6` ``
- Activated `virtualenv` with `. ./bin/activate`
- Ran `pip install telegram`
- `./bin/python bot.py` gives

```Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    from telegram import Emoji, ParseMode, TelegramError, Update
ImportError: cannot import name 'Emoji'```

**Comment by allbinmani** [comment]
Solution found!
It seems the Emoji support was deprecated in `python-telegram-bot` V5.1, so in order to make it work you have to install V5.0 using
`pip install python-telegram-bot==5.0`

**Comment by zimler** [comment]
Well, how about that. Good detective work. I'll try that later this week and report back. Depreciated on purpose? But why...
