### ISSUE TITLE
bot keeps saying "Sorry, only the person who invited me can do that."

### ISSUE THREAD

**Issue by bendani** [jh0ker/welcomebot#9]
I have installed python 3.4 with pickledb and telegram python-telegram-bot 5.1.1
but bot doesn't seems to respond my commands.
he just keeps saying "Sorry, only the person who invited me can do that."

this is the error I get on the python process:
2018-08-23 08:34:21,551 - telegram.ext.dispatcher - ERROR - run_async function raised exception
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/telegram/ext/dispatcher.py", line 158, in _pooled
    promise.run()
  File "/usr/lib/python3.4/site-packages/telegram/utils/promise.py", line 36, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "bot.py", line 66, in send_async
    bot.sendMessage(*args, **kwargs);
  File "/usr/lib/python3.4/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/telegram/bot.py", line 152, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/lib/python3.4/site-packages/telegram/utils/request.py", line 201, in post
    **urlopen_kwargs)
  File "/usr/lib/python3.4/site-packages/telegram/utils/request.py", line 146, in _request_wrapper
    raise Unauthorized()
telegram.error.Unauthorized: Unauthorized

can you please advise what is causing it?

**Comment by engelsit** [comment]
Bug is present. After the long period of offline, the bot does not listen to the Administrator. Reinvite does not help.

**Comment by herwincamargo** [comment]
Same issue here, bot say:
"Sorry, only the person who invited me can do that.

**Comment by AlainLaurent** [comment]
Inviting isn't working anymore.
Work around that I use :
The first person that runs /setadmin will be added to the db and can lock/unlock/...
Just add a new handler and function

`dp.add_handler(CommandHandler("setadmin", set_admin))`

```
def set_admin(update, context):
    chat_id = update.message.chat.id
    admin_id = update.message.from_user.id
    admin_key = str(chat_id) + "_adm"
    
    if not db.exists(admin_key):
        db.set(str(chat_id) + "_adm", admin_id)
        send_async(context, chat_id=chat_id, text="Admin set!")
    else:
        send_async(context, chat_id=chat_id, text="Admin already set!")
```

Thx Jannes Höke for this bot, learned a lot from it !
